version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    restart: always
    ports:
      - 5001:5000
    volumes:
      - .:/usr/src/app
    environment:
      - DATABASE_URL=$DATABASE_URL
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ttf-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
volumes:
  ttf-data:
